((topmost-intro 1))
((defun-block-intro 1))
((inlambda) (defun-block-intro 16))
((inlambda) (inline-close 16))
((arglist-cont-nonempty 16 27) (arglist-cont-nonempty 16 34) (arglist-cont-nonempty 16 40) (comment-intro))
((arglist-cont-nonempty 16 27) (arglist-cont-nonempty 16 34) (arglist-cont-nonempty 16 40))
((defun-close 1))
