((topmost-intro <0,0>) (cpp-macro))
((topmost-intro <1,0>) (cpp-macro))
((cpp-define-intro <1,0>))
((statement <1,4>))
((topmost-intro <4,0>) (cpp-macro))
((topmost-intro <5,0>) (comment-intro))
((topmost-intro <6,0>))
((brace-list-intro <1,0>))
((brace-list-entry <1,4>))
((brace-list-entry <2,4>))
((brace-list-close <4,0>))
