((topmost-intro <0,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((inclass <2,0>) (topmost-intro <2,0>))
((defun-block-intro <1,4>))
((statement-block-intro <1,8>))
((block-close <2,8>))
((statement <3,8>))
((statement <4,8>))
((statement-block-intro <1,8>))
((block-close <2,8>))
((inline-close <8,4>))
((inclass <11,0>) (topmost-intro <1,0>))
((class-close <12,0>))
