((topmost-intro <0,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((inclass <2,0>) (topmost-intro <2,0>))
((defun-block-intro <1,4>))
((statement <1,8>))
((inline-close <3,4>))
((inclass <6,0>) (topmost-intro <1,0>))
((class-close <7,0>))
