((topmost-intro <0,0>) (comment-intro))
((c <1,0>))
((topmost-intro <2,0>))
((topmost-intro <3,0>) (cpp-macro))
((cpp-macro-cont <1,0>))
((topmost-intro <5,0>) (cpp-macro))
((topmost-intro <6,0>) (cpp-macro))
((arglist-cont-nonempty <1,0> <1,4>))
((topmost-intro <8,0>) (cpp-macro))
((topmost-intro <9,0>) (cpp-macro))
((cpp-define-intro) (statement <1,0>))
((topmost-intro <11,0>) (cpp-macro))
((cpp-define-intro) (arglist-cont-nonempty <1,0> <1,13>))
((cpp-define-intro) (arglist-close <2,0> <2,13>))
((topmost-intro <14,0>) (cpp-macro))
((cpp-define-intro) (arglist-intro <1,0> <1,13>))
((arglist-cont <1,8>))
((cpp-define-intro) (arglist-close <3,0> <3,13>))
((topmost-intro <18,0>) (cpp-macro))
((arglist-cont-nonempty <1,0> <1,9>))
((arglist-close <2,0> <2,9>))
((cpp-define-intro <3,0>))
((topmost-intro <22,0>))
((topmost-intro <23,0>))
((defun-block-intro <1,0>))
((statement <1,4>) (cpp-macro))
((cpp-macro-cont <1,0>))
((statement <3,4>) (cpp-macro))
((statement <4,4>) (cpp-macro))
((arglist-cont-nonempty <1,0> <1,4>))
((statement <6,4>) (cpp-macro))
((statement <7,4>) (cpp-macro))
((cpp-define-intro) (statement-cont <1,0>))
((statement <9,4>) (cpp-macro))
((cpp-define-intro) (arglist-cont-nonempty <1,0> <1,13>))
((cpp-define-intro) (arglist-close <2,0> <2,13>))
((statement <12,4>) (cpp-macro))
((cpp-define-intro) (arglist-intro <1,0> <1,13>))
((arglist-cont <1,8>))
((cpp-define-intro) (arglist-close <3,0> <3,13>))
((statement <16,4>) (cpp-macro))
((arglist-cont-nonempty <1,0> <1,9>))
((arglist-close <2,0> <2,9>))
((cpp-define-intro <3,0>))
((defun-close <21,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((arglist-cont-nonempty <1,0> <1,6>) (cpp-macro))
((cpp-macro-cont <1,0>))
((arglist-cont-nonempty <3,0> <3,6>) (cpp-macro))
((arglist-cont-nonempty <4,0> <4,6>) (cpp-macro))
((arglist-cont-nonempty <1,0> <1,4>))
((arglist-cont-nonempty <6,0> <6,6>) (cpp-macro))
((arglist-cont-nonempty <7,0> <7,6>) (cpp-macro))
((arglist-cont-nonempty <8,0> <8,6>))
((arglist-cont-nonempty <9,0> <9,6>) (cpp-macro))
((cpp-define-intro) (arglist-cont-nonempty <1,0> <1,13>))
((cpp-define-intro) (arglist-close <2,0> <2,13>))
((arglist-cont-nonempty <12,0> <12,6>) (cpp-macro))
((cpp-define-intro) (arglist-intro <1,0> <1,13>))
((arglist-cont <1,11>))
((cpp-define-intro) (arglist-close <3,0> <3,13>))
((arglist-cont-nonempty <16,0> <16,6>) (cpp-macro))
((arglist-cont-nonempty <1,0> <1,9>))
((arglist-close <2,0> <2,9>))
((cpp-define-intro <3,0>))
((arglist-close <20,0> <20,6>))
