((topmost-intro <0,0>) (cpp-macro))
((cpp-define-intro <1,0>))
((brace-list-close <1,4>))
((statement <2,4>))
((brace-list-close <1,4>))
((topmost-intro <5,0>))
((topmost-intro <6,0>) (cpp-macro))
((cpp-define-intro <1,0>))
((statement <1,4>))
((substatement <1,4>))
((substatement <1,8>))
((else-clause <2,8>))
