((topmost-intro <0,0>))
((member-init-intro <1,0>))
((defun-block-intro <2,0>))
((defun-close <3,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((innamespace <1,0>) (topmost-intro <1,0>))
((inclass <1,4>) (access-label <1,4>))
((inclass <2,4>) (topmost-intro <2,0>))
((member-init-intro <1,8>))
((member-init-cont <1,12>))
((inclass <5,4>) (inline-open))
((class-close <6,4>))
((namespace-close <8,0>))
