((topmost-intro 1))
((member-init-cont 23))
((defun-open 1))
((topmost-intro 79))
((topmost-intro 79))
((class-open 83))
((inclass 96) (topmost-intro 96))
((member-init-cont 117))
((inclass 96) (inline-open))
((class-close 83))
