Dum& Dum::operator+ () {}
Dum& Dum::operator- () {}
Dum& Dum::operator* () {}
Dum& Dum::operator/ () {}
Dum& Dum::operator% () {}
Dum& Dum::operator^ () {}
Dum& Dum::operator& () {}
Dum& Dum::operator| () {}
Dum& Dum::operator~ () {}
Dum& Dum::operator! () {}
Dum& Dum::operator= () {}
Dum& Dum::operator< () {}
Dum& Dum::operator> () {}
Dum& Dum::operator+= () {}
Dum& Dum::operator-= () {}
Dum& Dum::operator*= () {}
Dum& Dum::operator/= () {}
Dum& Dum::operator%= () {}
Dum& Dum::operator^= () {}
Dum& Dum::operator&= () {}
Dum& Dum::operator|= () {}
Dum& Dum::operator<< () {}
Dum& Dum::operator>> () {}
Dum& Dum::operator>>= () {}
Dum& Dum::operator<<= () {}
Dum& Dum::operator== () {}
Dum& Dum::operator!= () {}
Dum& Dum::operator<= () {}
Dum& Dum::operator>= () {}
Dum& Dum::operator&& () {}
Dum& Dum::operator|| () {}
Dum& Dum::operator++ () {}
Dum& Dum::operator-- () {}
Dum& Dum::operator, () {}
Dum& Dum::operator->* () {}
Dum& Dum::operator-> () {}
Dum& Dum::operator() () {}
Dum& Dum::operator[] () {}
// foo
