((topmost-intro 1))
((class-open 1))
((inclass 11) (topmost-intro 11))
((inclass 11) (inline-open))
((defun-block-intro 32))
((statement-cont 35))
((statement-cont 35))
((statement-cont 35))
((statement-cont 35))
((statement-cont 35))
((inline-close 32))
((class-close 1))
