((topmost-intro <0,0>) (comment-intro))
((topmost-intro <1,0>) (comment-intro))
((topmost-intro <2,0>))
((topmost-intro <3,0>))
((topmost-intro-cont <1,0>))
((class-open <2,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((topmost-intro-cont <1,4>))
((inclass <3,0>) (inline-open))
((class-close <6,0>))
