((topmost-intro <0,0>))
((statement-cont <1,0>))
((substatement <2,0>))
((statement-cont <1,4>))
((substatement <2,4>))
((statement-cont <1,8>))
((else-clause <4,4>))
((substatement <1,4>))
((statement-cont <1,8>))
((arglist-intro <1,12> <1,12>))
((arglist-cont <1,16>))
((arglist-close <3,12> <3,12>))
((else-clause <12,0>))
((substatement <1,0>))
((topmost-intro <1,0>))
((statement-cont <1,0>))
((substatement <2,0>))
((statement-cont <1,4>))
((substatement <2,4>))
((statement-cont <1,8>))
((arglist-cont-nonempty <1,12> <1,12>))
((arglist-close <2,12> <2,12>))
((else-clause <6,4>))
((substatement <1,4>))
((statement-cont <1,8>))
((topmost-intro <1,0>))
((substatement <1,0>))
((statement-cont <1,4>))
((do-while-closure <3,0>))
((statement-cont <1,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>) (cpp-macro))
((cpp-define-intro <1,0>))
((statement-cont <1,4>))
((substatement <2,4>))
((substatement <1,8>))
((else-clause <2,8>))
((substatement <1,8>))
((else-clause <6,4>))
((substatement <1,4>))
((statement <8,4>))
((statement-cont <1,4>))
((substatement <2,4>))
((substatement <1,8>))
((else-clause <2,8>))
((substatement <1,8>))
((statement <6,4>))
((substatement <1,4>))
((do-while-closure <2,4>))
((statement-cont <1,4>))
((topmost-intro <21,0>))
((topmost-intro <22,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-intro <1,4> <1,5>))
((statement-cont <1,8>))
((substatement <2,8>))
((substatement <1,12>))
((else-clause <2,12>))
((substatement <1,12>))
((else-clause <6,8>))
((substatement <1,8>))
((arglist-cont <8,8>))
((statement-cont <1,8>))
((substatement <2,8>))
((substatement <1,12>))
((else-clause <2,12>))
((substatement <1,12>))
((arglist-cont <14,8>))
((substatement <1,8>))
((do-while-closure <2,8>))
((statement-cont <1,8>))
((arglist-close <19,4> <19,5>))
((defun-close <21,0>))
