(global-set-key (kbd "C-M-v") 'pager-page-up)
(global-set-key "\C-v"	'pager-page-down)
(global-set-key [next]	'pager-page-down)
(global-set-key [prior]	'pager-page-up)
(global-set-key '[M-up]	'pager-row-up)
(global-set-key '[M-kp-8] 'pager-row-up)
(global-set-key '[M-down] 'pager-row-down)
(global-set-key '[M-kp-2] 'pager-row-down)
